var flag = true;
var num = 2;
var word = "This is a word";
var arraynum = [1, 2, 3];
console.log("The value assigned to flag is: " + flag);
console.log("The value assigned to num is: " + num);
console.log("The value assigned to word is: " + word);
console.log("The value for index 0 of the array is: " + arraynum[0]);
console.log("The value for index 1 of the array is: " + arraynum[1]);
console.log("The value for index 2 of the array is: " + arraynum[2]);
